# Generated by Django 6.0.2 on 2026-03-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associado',
            old_name='criado_em',
            new_name='data_cadastro',
        ),
        migrations.AddField(
            model_name='associado',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='associado',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
