# Generated by Django 6.0.2 on 2026-03-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associado', '0002_rename_criado_em_associado_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associado',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='associados/'),
        ),
        migrations.AddField(
            model_name='associado',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='status',
            field=models.CharField(default='Ativo', max_length=20),
        ),
    ]
